version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: /server-go
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directories: [/server-node, /client, /bench, /test/browser]
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /server-python
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directories: [/docker, /server-go, /server-node, /server-python]
    schedule: { interval: weekly }
