import { test, expect, Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

test.setTimeout(60_000);

/**
 * The minified bundle must behave identically to the source it is built from.
 *
 * The specific worry is fingerprinting. The widget hashes canvas and WebGL
 * output into signals the server scores, and those hashes are derived from
 * string literals and drawing calls in this file. If a minifier altered any of
 * that, every fingerprint would shift — silently, and only for the CDN build,
 * so self-hosted and CDN users would be scored differently for the same browser.
 *
 * build.js asserts the fingerprint literals survive; this asserts the fingerprint
 * *outputs* match, which is the claim that actually matters.
 *
 * Skips rather than fails when dist/ is absent: the bundle is generated by
 * `npm run build` in client/ and is not committed, so a fresh checkout that has
 * not built yet should not see a red test it cannot explain.
 */
const SOURCE = path.resolve(__dirname, '../../../client/fcaptcha.js');
const MINIFIED = path.resolve(__dirname, '../../../client/dist/fcaptcha.min.js');

const built = fs.existsSync(MINIFIED);

/** Serves a specific build at the widget URL, then reads back its signals. */
async function collectSignals(page: Page, bundlePath: string) {
  const body = fs.readFileSync(bundlePath, 'utf8');

  await page.route('http://localhost:3000/fcaptcha.js', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'application/javascript; charset=utf-8',
      body,
    })
  );
  await page.route('http://localhost:3000/__min__', (route) =>
    route.fulfill({
      status: 200,
      contentType: 'text/html; charset=utf-8',
      body: `<!doctype html><html lang="en"><body>
        <script src="http://localhost:3000/fcaptcha.js"></script>
        </body></html>`,
    })
  );

  await page.goto('http://localhost:3000/__min__');
  await page.waitForFunction(() => (window as any).FCaptcha !== undefined);

  return page.evaluate(() => {
    const signals = (window as any).FCaptcha.getSignals();
    return {
      version: (window as any).FCaptcha.version,
      languages: (window as any).FCaptcha.languages(),
      environmental: signals.environmental,
    };
  });
}

/**
 * Pulls out the values that must be byte-stable across builds.
 *
 * canvasHash.hash is the load-bearing one: it is a digest of text the widget
 * draws using string literals in the source, so it is precisely what a minifier
 * rewriting literals would move. The WebGL and audio values are read from the
 * driver rather than computed, so they are a weaker check, but a difference in
 * them would still mean the collector changed.
 */
function fingerprintOf(env: any) {
  return {
    canvas: env?.canvasHash?.hash ?? null,
    canvasLength: env?.canvasHash?.dataLength ?? null,
    webglRenderer: env?.webglInfo?.renderer ?? null,
    webglVendor: env?.webglInfo?.vendor ?? null,
  };
}

test.describe('minified bundle', () => {
  test.skip(!built, 'client/dist not built — run `npm run build` in client/');

  test('is meaningfully smaller than the source', async () => {
    const source = fs.statSync(SOURCE).size;
    const min = fs.statSync(MINIFIED).size;
    expect(min).toBeLessThan(source * 0.75);
  });

  test('reports the same version and language set as the source', async ({ page }) => {
    const fromSource = await collectSignals(page, SOURCE);
    const fromMin = await collectSignals(page, MINIFIED);

    expect(fromMin.version).toBe(fromSource.version);
    expect(fromMin.languages).toEqual(fromSource.languages);
  });

  test('produces identical fingerprints to the source', async ({ page }) => {
    // Same browser, same page context, two bundles: any difference is the
    // minifier's doing, not the environment's.
    const fromSource = await collectSignals(page, SOURCE);
    const fromMin = await collectSignals(page, MINIFIED);

    const a = fingerprintOf(fromSource.environmental);
    const b = fingerprintOf(fromMin.environmental);

    // Guard against the test passing because both sides are null.
    const present = Object.values(a).filter((v) => v !== null).length;
    expect(present, 'no fingerprints collected — the comparison proves nothing').toBeGreaterThan(0);

    expect(b).toEqual(a);
  });

  test('collects the same signal shape as the source', async ({ page }) => {
    const fromSource = await collectSignals(page, SOURCE);
    const fromMin = await collectSignals(page, MINIFIED);

    // Key sets, not values: plenty of environmental values are legitimately
    // time- or state-dependent within a single browser.
    const keys = (o: any) => Object.keys(o ?? {}).sort();
    expect(keys(fromMin.environmental)).toEqual(keys(fromSource.environmental));
  });
});
